### ISSUE TITLE
Add More Bind

### ISSUE THREAD

**Issue by Saints-5** [Mrcubix/Preset.Binding#1]
Please add more binds to option like to a keyboard key :)
Thank you! <3

**Comment by Mrcubix** [comment]
I don't understand what you want.

Preset Bindings only allow you to switch to another preset using your tablet's aux, pen buttons or pressure, because this is the only thing provided by OpenTabletDriver.

If what you meaning is switching profile using a keyboard key, then it's out of scope of a plugin.
Another app will be needed for that and it's not something i'm interested in making.
